mozapkpublisher/base.py
mozapkpublisher/get_apk.py
mozapkpublisher/push_apk.py

Thanks for spotting it @sylvestre ! r? 
I tested the patch manually with both python 2 and 3. I got the warning message in one case but not the other. Like said in that message, I also got some characters stripped

Fix what's new message not appearing in the logs

---

mozapkpublisher/push_apk.py
mozapkpublisher/test/test_push_apk.py

Requested by flod, and things seem to work well enough without that.

push_apk: remove special-casing of en-GB locale

---

.travis.yml
mozapkpublisher/get_apk.py
mozapkpublisher/test/integration/test_get_apk.py
mozapkpublisher/test/test_get_apk.py
tox.ini

~~Needs some integration tests~~
0.2.0 incoming!

get_apk: download() doesn't rename files anymore

---

mozapkpublisher/googleplay.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/test_googleplay.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/test/test_update_apk_description.py
mozapkpublisher/update_apk_description.py

The patch could have been smaller. We technically just needed to call `edit_service.update_listings()` in `_push_whats_new`. However, I wanted to be sure the data structures passed to googleplay.py were the same as in `update_apk_description.py` (that's the script I used yesterday to unlock the locales).
Hence, I first added more tests to googleplay.py to freeze the calls sent to google-api-python-client. Then, I changed the method parameters in EditService. Finally, the calls are made from push_apk.
I've been cautious because we don't have a way to manually test it, other than when it's in production.
cc @flodolo

Bug 1349039 - Add listings of new locales during push_apk

---

mozapkpublisher/googleplay.py

Fallout of #22. On python 2, this caused:
```
2017-03-28 15:15:03,300 - discovery.py - INFO - URL being requested: PUT https://www.googleapis.com/androidpublisher/v2/applications/org.mozilla.firefox/edits/12907616204018632884/apks/2015478529/listings/cs-CZ?alt=json
Traceback (most recent call last):
File "mozapkpublisher/push_apk.py", line 131, in <module>
main(__name__)
File "mozapkpublisher/push_apk.py", line 124, in main
PushAPK().run()
File "mozapkpublisher/push_apk.py", line 80, in run
self.upload_apks(apks)
File "mozapkpublisher/push_apk.py", line 64, in upload_apks
_update_or_create_all_locales(edit_service, release_channel, apk['version_code'])
File "mozapkpublisher/push_apk.py", line 99, in _update_or_create_all_locales
play_store_locale, apk_version_code, …
```

Python 2: Fix non-ASCII logs

---

mozapkpublisher/push_apk.py

Might avoid accidentally pushing an update to 100% instead of 10%.

Error out if using --rollout-percentage on a non-rollout track

---

mozapkpublisher/get_apk.py
mozapkpublisher/test/test_get_apk.py

While working on https://github.com/escapewindow/staging-release-upload/pull/1, I realized `_fetch_checksum_from_file` doesn't support paths like `update/target.mar` in the checksum file.
This fixes it.

get_apk/checksum: Allow files in subdirectories

---

mozapkpublisher/googleplay.py
mozapkpublisher/push_apk.py
mozapkpublisher/store_l10n.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/test/test_store_l10n.py
mozapkpublisher/test/test_update_apk_description.py
mozapkpublisher/update_apk_description.py

This PR:
* optimize the number of requests done to store_l10n and google play
* factorize the behaviors between push_apk and update_apk_description
* shuffle store_l10n to expose only what's necessary.
I tested both `push_apk.py` and `update_apk_description.py` manually with dry-run mode
After this PR, 0.4.0 should be released
r? @sylvestre

Upload nightly strings

---

mozapkpublisher/apk.py
mozapkpublisher/exceptions.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/test_apk.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/utils.py

With [aarch64 being around](https://bugzilla.mozilla.org/show_bug.cgi?id=1368484), let's make sure we don't mix up architectures. Somebody might do the mistake, manually.
I mainly moved the lines added in https://github.com/mozilla-releng/pushapkscript/pull/15 to mozapkpublisher.

Add check to verify APK architecures

---

mozapkpublisher/googleplay.py
mozapkpublisher/push_apk.py
mozapkpublisher/store_l10n.py
mozapkpublisher/test/test_store_l10n.py
mozapkpublisher/update_apk_description.py

I couldn't not fully test against `org.mozilla.focus` because:
a. I don't have the rights to modify this app
b. No APK has been uploaded yet. Hence Google Play returns: `No application was found for the given package name.`
The package name was taken from https://github.com/mozilla-mobile/focus-android/blob/09784e886254ae6a398b7156930ebd7efeb2dd91/app/src/main/java/org/mozilla/focus/FocusApplication.java#L6

update_apk_description: Support Firefox Focus

---

mozapkpublisher/googleplay.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/test/test_store_l10n.py
mozapkpublisher/update_apk_description.py

Fixes #37. Depends on #40. 
The content of the file isn't checked yet. I plan to do so in a follow up patch.

 push_apk.py: Pass listings/whatsnew via on-disk files 

---

.travis.yml
README.md
mozapkpublisher/get_apk.py
mozapkpublisher/get_l10n_strings.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/common/test_googleplay.py
mozapkpublisher/test/common/test_store_l10n.py
mozapkpublisher/test/common/test_utils.py
mozapkpublisher/test/integration/test_get_l10n_strings.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/test/test_update_apk_description.py
mozapkpublisher/update_apk_description.py
setup.py
tox.ini

Depends on #44
Keeping the Python 2 support is risky because of UTF-8 strings provided by https://l10n.mozilla-community.org/stores_l10n/.
This hasn't been a big issue until #41. Before then, @jcristau noted that non-ASCII languages didn't display properly, but they've been uploaded correctly.
#41 now reads UTF-8 strings from a JSON file. This requires some decoding, just like in  https://github.com/mozilla-releng/mozapkpublisher/pull/44/commits/f430c6d056e5323fd1fba75dbc53c09c6f77a63a#diff-7c3a9f88ff9e7a9a229e7fdda8bfe7a6R24. Sadly, decoding UTF-8 value back to ASCII doesn't preserve the UTF-8 characters.
Then, we should stop supporting Python 2, and make explicit that people need Python 3. Otherwise, somebody may end up uploading broken strings to Google Play.

Drop Python 2 support 

---

mozapkpublisher/common/exceptions.py
mozapkpublisher/common/store_l10n.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/common/test_store_l10n.py
mozapkpublisher/test/integration/test_get_l10n_strings.py
mozapkpublisher/update_apk_description.py
requirements-dev.txt

Depends on #45. Follow up of #41.
Let's make sure the strings coming from either https://l10n.mozilla-community.org/stores_l10n/ or a file are well-formated.

 Enforce incoming locales to comply to a given schema 

---

mozapkpublisher/common/apk/checker.py
mozapkpublisher/test/common/apk/test_checker.py

Removing the check because it's overly specific now, and redundant because we check for max number of package names.

Closes #53 - Remove unneeded check for distinct package names.

---

mozapkpublisher/common/apk/extractor.py

We have to go through a decoder because ZipFile.read returns bytes and
configparser wants str, but we don't need to go through disk.

Avoid temporary file when reading application.ini from an apk

---

mozapkpublisher/common/apk/checker.py
requirements-dev.txt

While working on Fennec related work, I remembered push_apk used regexes too. Beta is little bit weird in this example, this is why the condition looks awkward and less straightforward than the example.
As you may use the `mozilla-version` library, would you like to take a look at its usage, @Callek ? r?

Remove regex to infer the type of a Firefox version

---

mozapkpublisher/common/store_l10n.py
mozapkpublisher/get_l10n_strings.py
mozapkpublisher/test/common/test_store_l10n.py

stores_l10n used to expose https://l10n.mozilla-community.org/stores_l10n/api/v1/fx_android/translation/61/fr/
for instance, but now reports errors. Therefore, there is no need to
deprecate the command line argument. Let's just get rid of it.
Revert "Bug 1459181 - get_l10n_strings: fetch version-specific "whatsnew" section if provided"
This reverts commit d34a49ac9e8069ce9a176da54c390b3e5ccf0f40.

Bug 1496090 - get_l10n_strings: Do not call version specific URLs anymore

---

mozapkpublisher/common/apk/extractor.py

Perhaps the [`check_all_arch_and_api`](https://github.com/mozilla-releng/mozapkpublisher/blob/master/mozapkpublisher/common/apk/checker.py#L53) check should be removed, too :thinking:

Removes firefox_* extraction for reference-browser

---

mozapkpublisher/test/test_get_l10n_strings.py

Whenever we run our `get_l10n_strings` test, it creates a file in our `mozapkpublisher/test` directory that isn't `gitignore`'d.
I think that if our tests create temporary files, we should use a temporary directory (e.g.: what if we assert on such files in the future? The state should be clean).
This PR ensures that a temp directory is used for the environment-mutating test

Runs file-creating test in temporary directory

---

.travis.yml
README.md
setup.py
tox.ini

In #196, a python3.5-specific error broke these tests: https://travis-ci.org/mozilla-releng/mozapkpublisher/jobs/537876097#L849.
We don't use python 3.5 anymore in production. Scriptworker itself doesn't support this version anymore https://github.com/mozilla-releng/scriptworker/blob/c3953fccc8860073b1f87cf7cc50c89cdedba92d/setup.py#L93. 
On the other side, mozapkpublisher can be run on a local machine and Python 3.5 is supported for another year and a half. I think it's fine to remove this support, based on the usage of this package. What do you think @mitchhentges ?

Remove Python 3.5 support

---

CHANGELOG.md
mozapkpublisher/push_apk.py
mozapkpublisher/test/test_push_apk.py

@flodolo and I discussed during the Whistler All Hands. Google Play strings won't be owned by the L10n team anymore, Marketing will. So far, Marketing has updated them via the Web UI. Maybe they'll want to automate it. In the meantime, let's remove the automatic submission. 
If needed, we can bring it back thanks to the Git history. 
See #204 for more context.

Bug 1560876 - push_apk.py: Stop uploading Google Play strings

---

mozapkpublisher/check_rollout.py
mozapkpublisher/common/googleplay.py
mozapkpublisher/test/common/test_googleplay.py
mozapkpublisher/test/test_check_rollout.py
mozapkpublisher/test/test_push_apk.py

Fixed. It was a bug on the Google Play server. ~~Please don't review yet, the code is currently buggy. It returns:~~ 
```
2019-06-24 17:21:17,203 - extractor.py - INFO - Extracting metadata from a copy of "tmp/target-1.apk"...
2019-06-24 17:21:17,516 - extractor.py - INFO - Extracting metadata from a copy of "tmp/target-3.apk"...
2019-06-24 17:21:17,788 - extractor.py - INFO - Extracting metadata from a copy of "tmp/target-4.apk"...
2019-06-24 17:21:18,012 - extractor.py - INFO - Extracting metadata from a copy of "tmp/target.apk"...
2019-06-24 17:21:18,220 - checker.py - INFO - Checking APKs' metadata and content...
2019-06-24 17:21:18,221 - checker.py - INFO - Expected product types ['org.mozilla.fennec_aurora'] found
2019-06-24 17:21:18,221 - checker.py - INFO - Firefox version …
```

Bug 1560713 - Move to Google API v3

---

CHANGELOG.md
mozapkpublisher/check_rollout.py
mozapkpublisher/common/exceptions.py
mozapkpublisher/common/googleplay.py
mozapkpublisher/push_apk.py
mozapkpublisher/test/common/test_googleplay.py
mozapkpublisher/test/test_check_rollout.py
mozapkpublisher/test/test_push_apk.py
mozapkpublisher/test/test_update_apk_description.py
mozapkpublisher/update_apk_description.py

This breaks apart `EditService`:
* Transactions (including committing) are now represented by:
`with WritableGooglePlay.transaction() as google_play:`
* Managing real vs mock API has been split into the `GooglePlayConnection` abstraction
* Read-only logic is simpler than write logic (no need to commit after), so it's split into a different class and made easier to use.
-----
@JohanLorenzo I'm pretty happy with these changes, though I'm on the fence about splitting `ReadOnlyGooglePlay` from `WritableGooglePlay`. My main reasoning for doing happened when I saw this:
```
with GooglePlay.transaction(connection, 'org.mozilla.firefox', do_not_commit=True) as google_play:
check_rollout(google_play, config.days)
```
When you're doing work that just requires read-only access, it's noisy to add …

Wraps transaction into separate class

---

CHANGELOG.md
mozapkpublisher/push_apk.py

Fixes https://tools.taskcluster.net/groups/FEM11DlNQ3m9RIk-03C5ZA/tasks/XRz-C2iITNWMFmFEBN5zJA/runs/0/logs/public%2Flogs%2Flive_backing.log which was reported by @ColinTheShots 
I tried to make a test out for this fix, but I didn't manage to get something simple enough. I think it's a good case for an integration test which would easier to do with bug 1575691. What do you think @mitchhentges

Fix focus/klar pushes which were sent in the same request

---

mozapkpublisher/common/store.py

Confirmed num_retries at https://googleapis.github.io/google-api-python-client/docs/epy/index.html

Bug 1905093 - set googleapiclient retries to 3

---

mozapkpublisher/common/apk/extractor.py
mozapkpublisher/common/main_logging.py
mozapkpublisher/test/common/apk/test_extractor.py
pyproject.toml
uv.lock

pyaxmlparser is basically the androguard apk parsing extracted out. This prevents having a bunch of dependencies like matplotlib getting installed when we're never ever going to be using them...
Fixes #258

Switch from androguard to pyaxmlparser

---

mozapkpublisher/common/utils.py
mozapkpublisher/test/common/test_utils.py
pyproject.toml
uv.lock

`is_firefox_version_nightly` is unused since 1e7d15de534ddd5bd5be09435523dc9c2008ebcc
`voluptuous` is unused since 5421be196182f94a8372ab95d630d553690f73bd
Fixes #270

Remove unused code and dependency

---

mozapkpublisher/common/apk/extractor.py
mozapkpublisher/sgs_api/__init__.py
mozapkpublisher/test/common/apk/test_extractor.py
mozapkpublisher/test/integration/test_upload_sgs.py
mozapkpublisher/test/sgs/test_submit.py

Turns out the API asks for a binarySeq for absolutely **no reason whatsoever** since they also expect every file name to be unique. I can't wait to discover that the filename cannot contain any `.` except for the extension or that there's a max size at 20 characters for no good reason. Given the rest of the API that would not even surprise me...
This is untested because we have to test in prod, they don't offer any way of having a test app; but that's how forms work, so hopefully they don't do anything stupid on their side...

Bug 1974870 - Upload APKs to SGS with a unique name

---

mozapkpublisher/common/apk/__init__.py
mozapkpublisher/common/apk/extractor.py
mozapkpublisher/test/common/apk/test_extractor.py

We depend on the architecture being present in the metadata when uploading binaries to the samsung galaxy store. This isn't the case for focus because we pass `skip_check_ordered_version_codes` which in turn leads to the architecture metadata not being extracted.
Unlike the other flagged metadata extraction, this one doesn't seem to be able to fail nor does it make this function slower (there's less than a 1% perf difference) so let's just unconditionally extract it and remove part of a footgun in the API.
Fixes #282

Always extract architecture metadata from APKs
